### ISSUE TITLE
x64 build

### ISSUE THREAD

**Issue by jacquesg** [minoca/swiss#1]
Is it possible to provide a 64-bit binary in addition to the 32-bit one?

**Comment by evangreen** [comment]
Hi Jacques. The 32-bit version should work fine on both 32 and 64 bit systems. That said, I do believe swiss compiles in 64-bit. Is there a particular reason you need 64-bit binaries?

**Comment by jacquesg** [comment]
The 32-bit binaries work great! I'm trying to eliminate the SysWOW64 overhead though, it becomes somewhat significant for workflows that are heavily reliant on UNIX tools.
